name: Version Bump & Release

on:
  push:
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.4"

      - name: Bump version in version.lua
        id: bump_version
        run: |
          VERSION_FILE="version.lua"
          OLD_VERSION=$(grep -oP "[0-9]+\.[0-9]+\.[0-9]+" $VERSION_FILE)
          IFS='.' read -r -a ver <<< "$OLD_VERSION"
          ver[2]=$((ver[2]+1))
          NEW_VERSION="${ver[0]}.${ver[1]}.${ver[2]}"
          sed -i "s/$OLD_VERSION/$NEW_VERSION/" $VERSION_FILE
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump version to ${{ steps.bump_version.outputs.new_version }}"
          tagging_message: "v${{ steps.bump_version.outputs.new_version }}"
          file_pattern: "version.lua"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.bump_version.outputs.new_version }}"
          name: "Release v${{ steps.bump_version.outputs.new_version }}"
          body: "Automated release by CI for version ${{ steps.bump_version.outputs.new_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
