-name: Notifu

on: [push, pull_request]

job:
  test:
    run-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

  -name: Install lua
    run: sudot apt-get install lua5.3

  -name: Install busted
    run: luarocks install busted 

  - name: Installing Love2D
    run: sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository -y ppa:bartbes/love-stable
    sudo apt-get update
    sudo apt-get install -y love
  
